### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by awolfe76** [cfpb/zip-backfill#8]
_Maybe do #10 first and add the step of `pip install -r requirements.txt` to the README._
- [ ] link to census `.shp`file needed to run `test.py`
- [ ] link to openaddresses data
- [ ] setup steps required
  - [ ] how to install python dependencies (pip)
  - [ ] run this, then this, then this
- [ ] give examples of code, eg `python test.py path/to/csv.csv path/to/output.csv tl_2015_us_zcta510.zip 10 -o`

**Comment by kgudel** [comment]
Closed by #11
